/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package plugin.resolution.constraints.app;

import plugin.resolution.constraints.list.LinkedList;

import static plugin.resolution.constraints.utilities.StringUtils.join;
import static plugin.resolution.constraints.utilities.StringUtils.split;
import static plugin.resolution.constraints.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
